version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build-and-test:
    macos:
      xcode: "13.1.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - xcode-select --install
      - ruby/install-deps
      - run: bundle install && bundle update
      - run:
          name: fastlane
          command: |
            bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
      - run: 
          name: install and run fastlane
          command: |
            brew install fastlane

workflows:
  build-and-test:
    jobs:
      - build-and-test

