# https://circleci.com/docs/2.0/testing-ios/
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

jobs:
  build-and-test:
    macos:
      xcode: 12.5.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  adhoc:
    macos:
      xcode: 12.5.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane adhoc
      - store_artifacts:
          path: output

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
          filters:
            branches:
              only: development
          requires:
            - build-and-test

  # build-and-test-ios:
  #   macos:
  #     xcode: 12.5.1 # Specify the Xcode version to use
      
  #   working_directory: /Users/distiller/project
  #   environment:
  #     FL_OUTPUT_DIR: output
  #     FASTLANE_LANE: test
  #   shell: /bin/bash --login -o pipefail
  #   steps:
  #     - checkout
  #     - run: bundle install
  #     - run:
  #         name: Fastlane
  #         command: bundle exec fastlane $FASTLANE_LANE
  #     - store_artifacts:
  #         path: output
  #     - store_test_results:
  #         path: output/scan


      # Collect XML test results data to show in the UI, and save the same XML
      # files under test-results folder in the Artifacts tab
      # - store_test_results:
      #     path: test_output
      # - store_artifacts:
      #     path: test_output
      #     destination: scan-output

